import { requireAdmin } from "../lib/admin.js";

import { jsonResponse } from "../lib/http.js";

export async function handleAdminLibraryRoutes(context) {
  const { request, url, sql, headers } = context;

  if (!url.pathname.startsWith("/admin/library")) {
    return null;
  }

  const admin = await requireAdmin(context);

  if (admin.response) {
    return admin.response;
  }

  /*
    ================================================
    LIST GAME LIBRARY

    GET /admin/library
    ================================================
  */

  if (url.pathname === "/admin/library" && request.method === "GET") {
    try {
      const rows = await sql`
          select
            id,
            library_code,
            game_name,
            platform,
            owned,
            enabled,
            request_type,
            schmeckle_cost,
            completed_at,
            notes,
            created_at,
            updated_at
          from game_library
          order by
            upper(platform),
            lower(game_name)
        `;

      return jsonResponse(
        {
          success: true,

          games: rows.map((row) => ({
            id: Number(row.id),

            library_code: row.library_code,

            game_name: row.game_name,

            platform: row.platform,

            owned: Boolean(row.owned),

            enabled: Boolean(row.enabled),

            request_type: row.request_type,

            schmeckle_cost: Number(row.schmeckle_cost),

            completed_at: row.completed_at,

            notes: row.notes,

            created_at: row.created_at,

            updated_at: row.updated_at,
          })),
        },
        200,
        headers,
      );
    } catch (error) {
      console.error("Admin library list failed:", error);

      return jsonResponse(
        {
          error: "Unable to load game library",
        },
        500,
        headers,
      );
    }
  }

  /*
    ================================================
    ADD GAME

    POST /admin/library/add

    {
      "game_name": "Battletoads",
      "platform": "NES",
      "owned": true,
      "enabled": true,
      "request_type": "schmeckles",
      "schmeckle_cost": 25000,
      "notes": ""
    }
    ================================================
  */

  if (url.pathname === "/admin/library/add" && request.method === "POST") {
    try {
      const body = await request.json();

      const gameName = String(body.game_name || "").trim();

      const platform = String(body.platform || "")
        .trim()
        .toUpperCase();

      const owned = body.owned !== false;

      const enabled = body.enabled !== false;

      const requestType = String(body.request_type || "schmeckles")
        .trim()
        .toLowerCase();

      const schmeckleCost = Number(body.schmeckle_cost ?? 25000);

      const notes = String(body.notes || "")
        .trim()
        .slice(0, 1000);

      const allowedRequestTypes = [
        "schmeckles",
        "donation",
        "community",
        "disabled",
      ];

      if (!gameName) {
        return jsonResponse(
          {
            error: "Game name is required",
          },
          400,
          headers,
        );
      }

      if (!platform) {
        return jsonResponse(
          {
            error: "Platform is required",
          },
          400,
          headers,
        );
      }

      if (!allowedRequestTypes.includes(requestType)) {
        return jsonResponse(
          {
            error: "Invalid request type",
          },
          400,
          headers,
        );
      }

      if (!Number.isInteger(schmeckleCost) || schmeckleCost < 0) {
        return jsonResponse(
          {
            error: "Invalid Schmeckle cost",
          },
          400,
          headers,
        );
      }

      /*
        Prevent duplicate title + platform.
      */

      const existing = await sql`
          select
            id,
            library_code,
            game_name,
            platform
          from game_library
          where
            lower(game_name) =
              lower(${gameName})

            and upper(platform) =
              upper(${platform})

          limit 1
        `;

      if (existing.length > 0) {
        return jsonResponse(
          {
            error: "Game already exists in library",

            library_code: existing[0].library_code,

            game_name: existing[0].game_name,

            platform: existing[0].platform,
          },
          409,
          headers,
        );
      }

      /*
        library_code is automatically
        generated by the Neon trigger.
      */

      const rows = await sql`
          insert into game_library (
            game_name,
            platform,
            owned,
            enabled,
            request_type,
            schmeckle_cost,
            notes,
            updated_at
          )
          values (
            ${gameName},
            ${platform},
            ${owned},
            ${enabled},
            ${requestType},
            ${schmeckleCost},
            ${notes || null},
            now()
          )
          returning
            id,
            library_code,
            game_name,
            platform,
            owned,
            enabled,
            request_type,
            schmeckle_cost,
            completed_at,
            notes,
            created_at,
            updated_at
        `;

      return jsonResponse(
        {
          success: true,

          game: {
            id: Number(rows[0].id),

            library_code: rows[0].library_code,

            game_name: rows[0].game_name,

            platform: rows[0].platform,

            owned: Boolean(rows[0].owned),

            enabled: Boolean(rows[0].enabled),

            request_type: rows[0].request_type,

            schmeckle_cost: Number(rows[0].schmeckle_cost),

            completed_at: rows[0].completed_at,

            notes: rows[0].notes,
          },
        },
        201,
        headers,
      );
    } catch (error) {
      console.error("Admin library add failed:", error);

      if (error && error.code === "23505") {
        return jsonResponse(
          {
            error: "Game already exists in library",
          },
          409,
          headers,
        );
      }

      return jsonResponse(
        {
          error: "Unable to add game",
        },
        500,
        headers,
      );
    }
  }

  /*
    ================================================
    UPDATE GAME

    POST /admin/library/update
    ================================================
  */

  if (url.pathname === "/admin/library/update" && request.method === "POST") {
    try {
      const body = await request.json();

      const libraryCode = String(body.library_code || "")
        .trim()
        .toUpperCase();

      if (!libraryCode) {
        return jsonResponse(
          {
            error: "Library code is required",
          },
          400,
          headers,
        );
      }

      const existing = await sql`
          select *
          from game_library
          where
            upper(library_code) =
              ${libraryCode}
          limit 1
        `;

      if (!existing.length) {
        return jsonResponse(
          {
            error: "Library game not found",
          },
          404,
          headers,
        );
      }

      const old = existing[0];

      const gameName =
        body.game_name !== undefined
          ? String(body.game_name).trim()
          : old.game_name;

      const platform =
        body.platform !== undefined
          ? String(body.platform).trim().toUpperCase()
          : old.platform;

      const owned =
        body.owned !== undefined ? Boolean(body.owned) : Boolean(old.owned);

      const enabled =
        body.enabled !== undefined
          ? Boolean(body.enabled)
          : Boolean(old.enabled);

      const requestType =
        body.request_type !== undefined
          ? String(body.request_type).trim().toLowerCase()
          : old.request_type;

      const schmeckleCost =
        body.schmeckle_cost !== undefined
          ? Number(body.schmeckle_cost)
          : Number(old.schmeckle_cost);

      const notes =
        body.notes !== undefined
          ? String(body.notes || "")
              .trim()
              .slice(0, 1000)
          : old.notes;

      const allowedRequestTypes = [
        "schmeckles",
        "donation",
        "community",
        "disabled",
      ];

      if (!gameName || !platform) {
        return jsonResponse(
          {
            error: "Game name and platform are required",
          },
          400,
          headers,
        );
      }

      if (!allowedRequestTypes.includes(requestType)) {
        return jsonResponse(
          {
            error: "Invalid request type",
          },
          400,
          headers,
        );
      }

      if (!Number.isInteger(schmeckleCost) || schmeckleCost < 0) {
        return jsonResponse(
          {
            error: "Invalid Schmeckle cost",
          },
          400,
          headers,
        );
      }

      const rows = await sql`
          update game_library
          set
            game_name =
              ${gameName},

            platform =
              ${platform},

            owned =
              ${owned},

            enabled =
              ${enabled},

            request_type =
              ${requestType},

            schmeckle_cost =
              ${schmeckleCost},

            notes =
              ${notes || null},

            updated_at =
              now()

          where
            upper(library_code) =
              ${libraryCode}

          returning
            id,
            library_code,
            game_name,
            platform,
            owned,
            enabled,
            request_type,
            schmeckle_cost,
            completed_at,
            notes,
            created_at,
            updated_at
        `;

      return jsonResponse(
        {
          success: true,

          game: {
            id: Number(rows[0].id),

            library_code: rows[0].library_code,

            game_name: rows[0].game_name,

            platform: rows[0].platform,

            owned: Boolean(rows[0].owned),

            enabled: Boolean(rows[0].enabled),

            request_type: rows[0].request_type,

            schmeckle_cost: Number(rows[0].schmeckle_cost),

            completed_at: rows[0].completed_at,

            notes: rows[0].notes,
          },
        },
        200,
        headers,
      );
    } catch (error) {
      console.error("Admin library update failed:", error);

      if (error && error.code === "23505") {
        return jsonResponse(
          {
            error: "Another library game already uses that title and platform",
          },
          409,
          headers,
        );
      }

      return jsonResponse(
        {
          error: "Unable to update game",
        },
        500,
        headers,
      );
    }
  }

  return jsonResponse(
    {
      error: "Admin library route not found",
    },
    404,
    headers,
  );
}
